### ISSUE TITLE
Where to find GPU firmware

### ISSUE THREAD

**Issue by fakuivan** [7coil/archlinux-on-ps4#2]
The kernel repo recommended by this guide provides a magical [firmware.zip](https://github.com/huzhekun/ps4-linux-5.3.7/raw/master/firmware.zip) needed to compile the amdgpu driver. Is there an official source for the binary blobs? I'm trying to automate the compilation process, and it'd be nice to be able to use the official source for these binaries, as there's no way to confirm that I or anyone else messed with them in any dumb or fishy way.

Ideally I would have opened an issue in [huzhekun/ps4-linux-5.3.7](https://github.com/huzhekun/ps4-linux-5.3.7), but it seems the author disabled issues.

**Comment by 7coil** [comment]
Absolutely no clue. Sorry.

**Comment by 7coil** [comment]
![image](https://user-images.githubusercontent.com/13886925/176308312-faf02cec-a0c1-4371-ac88-660b3ed3a98f.png)

On an unrelated note, it seems like _someone_ has been hardcoding the EDID for a 1080p Samsung (TV?) which is probably why everyone has been getting black screens on random other TVs and Monitors.
